name: flutter_map
description: A Dart implementation of Leaflet for Flutter apps
version: 0.5.5+2
authors:
- John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/flutter_map

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.2
  positioned_tap_detector: ^1.0.2
  transparent_image: ^1.0.0
  async: ^2.1.0
  validate: ^1.0.0
  intl: 0.15.8 # 时间
  flutter_image:
    git:
      url: http://git.ricent.com:8088/scm/git/flutter_image
      ref: ricent
  
  cached_network_image: 1.1.1
  # sqflite: ^1.1.5
  path_provider: ^1.2.0

dev_dependencies:
  pedantic: ^1.5.0
  flutter_test:
    sdk: flutter
  test: ^1.6.0
